<a href="https://colab.research.google.com/github/Bryce1010/-/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## 入门
### 张量
Tensors类似与numpy的ndarrays ,另外还可以在GPU上利用Tensors来加速计算。


In [0]:
from __future__ import print_function
import torch

In [11]:
x=torch.Tensor(5,3)
print(x)
y=torch.rand(5,3)
print(y)
print(y.size())
print(x+y)

tensor([[2.8962e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 3.6075e-01],
        [1.6927e+22, 1.7282e-04, 4.4156e-05],
        [4.3010e-05, 2.1782e-04, 2.1590e-04],
        [4.2467e+21, 2.6217e+20, 1.4423e-01]])
tensor([[0.9342, 0.0078, 0.8891],
        [0.1477, 0.5448, 0.3882],
        [0.5794, 0.8616, 0.2801],
        [0.7173, 0.2945, 0.8417],
        [0.7452, 0.6972, 0.1973]])
torch.Size([5, 3])
tensor([[9.3417e-01, 7.7850e-03, 8.8913e-01],
        [1.4771e-01,        nan, 7.4892e-01],
        [1.6927e+22, 8.6176e-01, 2.8013e-01],
        [7.1738e-01, 2.9467e-01, 8.4192e-01],
        [4.2467e+21, 2.6217e+20, 3.4157e-01]])


## 操作

In [18]:
print(x+y)
print(torch.add(x,y))
result=torch.Tensor(5,3)
print(torch.add(x,y,out=result))
y.add(x)

tensor([[9.3417e-01, 7.7850e-03, 8.8913e-01],
        [1.4771e-01,        nan, 7.4892e-01],
        [1.6927e+22, 8.6176e-01, 2.8013e-01],
        [7.1738e-01, 2.9467e-01, 8.4192e-01],
        [4.2467e+21, 2.6217e+20, 3.4157e-01]])
tensor([[9.3417e-01, 7.7850e-03, 8.8913e-01],
        [1.4771e-01,        nan, 7.4892e-01],
        [1.6927e+22, 8.6176e-01, 2.8013e-01],
        [7.1738e-01, 2.9467e-01, 8.4192e-01],
        [4.2467e+21, 2.6217e+20, 3.4157e-01]])
tensor([[9.3417e-01, 7.7850e-03, 8.8913e-01],
        [1.4771e-01,        nan, 7.4892e-01],
        [1.6927e+22, 8.6176e-01, 2.8013e-01],
        [7.1738e-01, 2.9467e-01, 8.4192e-01],
        [4.2467e+21, 2.6217e+20, 3.4157e-01]])


tensor([[9.3417e-01, 7.7850e-03, 8.8913e-01],
        [1.4771e-01,        nan, 7.4892e-01],
        [1.6927e+22, 8.6176e-01, 2.8013e-01],
        [7.1738e-01, 2.9467e-01, 8.4192e-01],
        [4.2467e+21, 2.6217e+20, 3.4157e-01]])

## Numpy 转换
将Tensor转换为numpy数组

In [21]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


将numpy转换为Tensor

In [22]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [23]:
x=x.cuda()
print(x)
y=y.cuda()
print(y)
print(x+y)

tensor([[2.8962e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 3.6075e-01],
        [1.6927e+22, 1.7282e-04, 4.4156e-05],
        [4.3010e-05, 2.1782e-04, 2.1590e-04],
        [4.2467e+21, 2.6217e+20, 1.4423e-01]], device='cuda:0')
tensor([[0.9342, 0.0078, 0.8891],
        [0.1477, 0.5448, 0.3882],
        [0.5794, 0.8616, 0.2801],
        [0.7173, 0.2945, 0.8417],
        [0.7452, 0.6972, 0.1973]], device='cuda:0')
tensor([[9.3417e-01, 7.7850e-03, 8.8913e-01],
        [1.4771e-01,        nan, 7.4892e-01],
        [1.6927e+22, 8.6176e-01, 2.8013e-01],
        [7.1738e-01, 2.9467e-01, 8.4192e-01],
        [4.2467e+21, 2.6217e+20, 3.4157e-01]], device='cuda:0')
