<a href="https://colab.research.google.com/github/Bryce1010/-/blob/master/01-basic/Pytorch-basic/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms


# ================================================================== #
#                         Table of Contents                          #
# ================================================================== #

# 1. Basic autograd example 1               (Line 25 to 39)
# 2. Basic autograd example 2               (Line 46 to 83)
# 3. Loading data from numpy                (Line 90 to 97)
# 4. Input pipline                          (Line 104 to 129)
# 5. Input pipline for custom dataset       (Line 136 to 156)
# 6. Pretrained model                       (Line 163 to 176)
# 7. Save and load model                    (Line 183 to 189) 






# ================================================================== #
#                     1. Basic autograd example 1                    #
# ================================================================== #





# Create tensors
x=torch.tensor(1.,requires_grad=True)
w=torch.tensor(2.,requires_grad=True)
b=torch.tensor(3.,requires_grad=True)


#Build a computational graph
y=w*x+b

#Computer gradients
y.backward()


# Print out the gradients
print(x.grad)
print(w.grad)
print(b.grad)


tensor(2.)
tensor(1.)
tensor(1.)


In [5]:
# ================================================================== #
#                    2. Basic autograd example 2                     #
# ================================================================== #


# Create tensors of shape (10,3) and　(10,2)
x=torch.randn(10,3)
y=torch.randn(10,2)

# Build a fully connected layer
linear=nn.Linear(3,2)
print(linear.weight)
print(linear.bias)


Parameter containing:
tensor([[ 0.1773,  0.1953,  0.1885],
        [-0.5356, -0.2540, -0.1925]], requires_grad=True)
Parameter containing:
tensor([-0.4133, -0.3364], requires_grad=True)


In [6]:
# Build loss function and optimizer
criterion=nn.MSELoss() # 均方损失函数
optimizer=torch.optim.SGD(linear.parameters(),lr=0.01)

# Forward pass
pred=linear(x)

# Compute pass
loss=criterion(pred,y)
print('loss:',loss.item())

loss: 3.2596068382263184


In [0]:
# Backward pass.
loss.backward()



In [10]:
# Print out the gradients.
print('dL/dW: ',linear.weight.grad)
print('dL/dB: ',linear.bias.grad)

dL/dW:  tensor([[ 0.8013,  0.6247,  0.9731],
        [-0.6444, -1.0104, -1.0978]])
dL/dB:  tensor([-0.8906, -0.6364])


In [12]:
# 1-step gradient descent
optimizer.step()


# You can also perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)


# Print out the loss after 1-step gradient descent
pred=linear(x)
loss=criterion(pred,y)
print('loss after 1-step optimization: ',loss.item())


loss after 1-step optimization:  3.1449742317199707


In [0]:
# ================================================================== #
#                     3. Loading data from numpy                     #
# ================================================================== #

# Create a numpy array
x=np.array([[1,2],[3,4]])

# Convert the numpy array to a torch tensor
y=torch.from_numpy(x)

# Convert the torch tensor to a numpy array
z=y.numpy()




In [15]:
# ================================================================== #
#                         4. Input pipline                           #
# ================================================================== #

# Download and construct CIFAR-10 dataset.
train_dataset=torchvision.datasets.CIFAR10(root='../../data',
                                          train=True,
                                          transform=transforms.ToTensor(),
                                          download=True)





In [16]:
# Fetch one data pair (read data from disk)
image, label =train_dataset[0]
print(image.size())
print(label)

torch.Size([3, 32, 32])
6


In [0]:
# data loader (this provides queues and threads in a very simple way.)
train_loader=torch.utils.data.DataLoader(dataset=train_dataset,
                                        batch_size=64,
                                        shuffle=True)

# When iteration starts, queue and thread start to load data from files 
data_iter=iter(train_loader)


In [20]:
print(data_iter)

In [0]:
# Mini-batch images and labels
images,labels=data_iter.next()

In [21]:
print(images,labels)

tensor([[[[0.1765, 0.1176, 0.1098,  ..., 0.6118, 0.5686, 0.5059],
          [0.1804, 0.1294, 0.1451,  ..., 0.5686, 0.5294, 0.4471],
          [0.1922, 0.1569, 0.1843,  ..., 0.3961, 0.4000, 0.4353],
          ...,
          [0.2196, 0.2275, 0.2353,  ..., 0.2824, 0.2824, 0.2824],
          [0.2078, 0.2157, 0.2196,  ..., 0.2706, 0.2784, 0.2784],
          [0.1922, 0.2000, 0.2078,  ..., 0.2627, 0.2706, 0.2706]],

         [[0.1176, 0.0745, 0.0627,  ..., 0.4588, 0.4000, 0.3333],
          [0.1176, 0.0824, 0.0902,  ..., 0.4392, 0.3922, 0.3098],
          [0.1294, 0.0980, 0.1216,  ..., 0.3020, 0.3020, 0.3176],
          ...,
          [0.2157, 0.2275, 0.2353,  ..., 0.2824, 0.2824, 0.2824],
          [0.2000, 0.2118, 0.2235,  ..., 0.2706, 0.2784, 0.2784],
          [0.1843, 0.1961, 0.2078,  ..., 0.2667, 0.2706, 0.2745]],

         [[0.0549, 0.0235, 0.0196,  ..., 0.2118, 0.1843, 0.1255],
          [0.0549, 0.0275, 0.0392,  ..., 0.1843, 0.1608, 0.1176],
          [0.0510, 0.0353, 0.0549,  ..., 0

In [0]:
# Actual usage of the data loader is as below
for images,labels in train_loader:
  # Training code shoule be written here.
  pass


In [0]:
# ================================================================== #
#                5. Input pipline for custom dataset                 #
# ================================================================== #


# You should build your custom dataset as below.
class CustomDataset(torch.utils.data.Dataset):
  def __init__(self):
    # TODO
    # 1. Initialize file paths or a list of file names.
    pass
  def __getitem__(self,index):
    # TODO
    # 1. Read one data from file (e.g. using numpy.fromfile, PIL.image.open).
    # 2. Preprocess the data (e.g. torchvision.Transform).
    # 3. Return a data pair (e.g. image and lable).
    pass
  def __len__(self):
    # You should change 0 to the total size of your dataset.
    return 0
 

# You can use the default prebuilt data loader .
custom_dataset=CustomDataset()
train_loader=torch.utils.data.DataLoader(dataset=custom_dataset,
                                        batch_size=64,
                                        shuffle=True)


In [27]:

# ================================================================== #
#                        6. Pretrained model                         #
# ================================================================== #


# Download and load the pretrained ResNet-18
resnet=torchvision.models.resnet18(pretrained=True)

# If you want to finetune only the top layer of the model, set as below.
for param in resnet.parameters():
  param.requiresf_grad=False
  
  
# Replace the top layer for finetuning.
resnet.fc=nn.Linear(resnet.fc.in_features,100) # 100 is an example


# Forward pass.
images=torch.randn(64,3,224,224)
outputs=resnet(images)
print(outputs.size()) # (64,100)

torch.Size([64, 100])


In [0]:
# ================================================================== #
#                      7. Save and load the model                    #
# ================================================================== #


# Save and load the entire model.
torch.save(resnet,'model.ckpt')
model=torch.load('model.ckpt')

# Save and load only the model parameters(recommended).
torch.save(resnet.state_dict(),'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))
